name: Tests Run 

on:

  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI Build
    steps:
    - name: Checkout
      uses: actions/checkout@v3


    - name: Run tests and collect coverage
      run:  ./run_tests.sh
