name: Tests Run 

on:

  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      keycloak:
        image: quay.io/keycloak/keycloak:latest
        env:
          KEYCLOAK_ADMIN : admin 
          KEYCLOAK_ADMIN_PASSWORD : admin 
          KEYCLOAK_HOST : localhost 
          KEYCLOAK_PORT : 8080
        options: --name keycloak --hostname keycloak
        ports:
          - 8080:8080
    name: CI Build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

  
    - name: Run tests and collect coverage
      env:
        KEYCLOAK_ADMIN : admin 
        KEYCLOAK_ADMIN_PASSWORD : admin 
        KEYCLOAK_HOST : keycloak 
        KEYCLOAK_PORT : 8080
      run:  ./run_tests.sh


    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: code-coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Output to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
